-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES

FROM PRODUCT A JOIN OFFLINE_SALE B
     ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID
ORDER BY SUM(PRICE*SALES_AMOUNT) DESC, PRODUCT_CODE ASC;