-- 코드를 입력하세요
-- FOOD_PRODUCT 테이블
-- FOOD_ORDER 식품 주문 정보
SELECT 

A.PRODUCT_ID,
A.PRODUCT_NAME,
-- (A.PRICE * B.AMOUNT) AS TOTAL_SALES
-- 총 매출
SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES


FROM FOOD_PRODUCT A 
    JOIN 
        FOOD_ORDER B
        -- 조인 조건
    ON A.PRODUCT_ID = B.PRODUCT_ID

WHERE 
    -- MONTH(PRODUCE_DATE) = '5' AND YEAR(PRODUCE_DATE)='2022'
    B.PRODUCE_DATE BETWEEN '2022-05-1 00:00:00' AND '2022-05-31 00:00:00'

GROUP BY A.PRODUCT_ID

ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;
;